content:
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    format: md
    fields:
      - name: title
        label: Titlu
        type: string
      - name: date
        label: Data
        type: date
      - name: description
        label: Descriere
        type: text
      - name: content
        label: Conținut
        type: rich-text

  - name: gallery
    label: Galerie Foto
    type: collection
    path: src/content/gallery
    format: md
    fields:
      - name: title
        label: Titlu
        type: string
      - name: pubDate
        label: Data
        type: date
      - name: description
        label: Descriere
        type: text

  - name: videos
    label: Video
    type: collection
    path: src/content/videos
    format: md
    fields:
      - name: title
        label: Titlu
        type: string
      - name: pubDate
        label: Data
        type: date
      - name: external_url
        label: Link YouTube/Vimeo
        type: string
      - name: description
        label: Descriere
        type: text

  - name: audio
    label: Muzică
    type: collection
    path: src/content/audio
    format: md
    fields:
      - name: title
        label: Titlu
        type: string
      - name: pubDate
        label: Data
        type: date
      - name: audio_file
        label: Fișier Audio (URL)
        type: string
      - name: description
        label: Descriere
        type: text
        